### ISSUE TITLE
Review comments #1: function documentation

### ISSUE THREAD

**Issue by csherwood-usgs** [esturdivant-usgs/BI-geomorph-extraction#33]
Functions could use a little more documentation. I recommend you establish your own documentation style for functions and classes...one that is not incompatible with sphinx. I like to specify the type and, dimensions of the arguments. I think my style is compatible with sphinx...it looks like the Google style here:  https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

My style looks like this:

```python
 class bmPoint:
    """
    Instantiate a three dimensional point object in regular coordinate space
    
    p = bmPoint(x, y, [z])
    
    Args:
        x: x (Easting) coordinate [length]
        y: y (Northing) coordinate [length]
        z: z (Elevation) coordinate [length; optional: defaults to 0.0 if not specified]  
    
    Returns:
        p: point of type bmPoint with x,y coordinates [length]
        
    Attributes:
        p.x: x (Easting) coordinate [length]
        p.y: y (Northing) coordinate [length]
        p.z: z (Elevation) coordinate [length; optional: defaults to 0.0 if not specified] 
    """
    def __init__(self, x, y, z=0.0):
        self.x = x
        self.y = y
        self.z = z
        
def bmDist2D(p1,p2):
    """
    Calculate distance between two bmPoint objects in the x, y plane
    
    dist = bmDist2D(p1, p2)
    
    Args:
        p1: point of type bmPoint with x,y coordinates [length]
        p2: point of type bmPoint with x,y coordinates [length]
    Returns:
        dist: Euclian distance between the points [length]
    """
    dx = p2.x-p1.x
    dy = p2.y-p1.y
    return(np.sqrt(dx**2+dy**2))
```

**Comment by esturdivant-usgs** [comment]
In commits b0da006 and d25e1eb07bcb43ee9386a00fbef5c475f8b5e804 I add function documentation based on python3 function annotations ([PEP-3107](https://www.python.org/dev/peps/pep-3107/)). All functions now include a description at the beginning in triple quotes and where I deemed useful, they the argument type is provided as parameter annotation.
