### ISSUE TITLE
Review comments #2 Document broader context for this software

### ISSUE THREAD

**Issue by csherwood-usgs** [esturdivant-usgs/BI-geomorph-extraction#35]
I was unsure what this software does and where it falls in the overall workflow. I recommend you modify the Overview section of the README.md to specify what, exactly, the products of this software are, and generally what is required as input. The "How to Implement" section does a nice job of specifying the details of the required inputs, but a few sentences in the Overview would help orient the reader. A figure depicting the geomorphology variables, or a table of inputs to the Bayesian model, would greatly clarify things.

Acronyms: spell out acronyms the first time in the README.md (NASC, DEM (done), Ortho, NAD83, UTM,  Esri (ESRI?), 

I noted that much of the input data are in lat/lon (WGS84). Should you outline a workflow for preparing these required inputs (converting to recommended NAD83; splitting shoreline, dune crest, dune toe points)?

**Comment by esturdivant-usgs** [comment]
633620e12c99af565b0586bfd9dd4cfad84a2f51 adds a table of variables to the overview section of the README.

We'd like to refer users to the methods report as much as possible. However, I'll continue to add contextual information. 

Still to do:
- check all acronyms
- address comment about WGS84 lat/long. Some of the conversions from WGS84 to NAD83 happen automatically in the code.
- possibly add workflow to split shoreline, dune crest, and dune toe points

**Comment by esturdivant-usgs** [comment]
4b4c922be06a9fb583fe6801f543e9c2cd24fb88 ensures there are no unexplained acronyms and removes the use of prepper.ipynb from the description.

**Comment by esturdivant-usgs** [comment]
Split into issues #41  and #42.
