### ISSUE TITLE
No PII found. Suggest deleting the temp folder in final version

### ISSUE THREAD

**Issue by zdefne-usgs** [esturdivant-usgs/BI-geomorph-extraction#36]
I reviewed the code and did not find any PII in the core scripts. There a few comments that are case specific, and can be left out prior to the release. e.g. 
https://github.com/esturdivant-usgs/BI-geomorph-extraction/blob/9d850847209610eff0c0408c6479d018f7b78b9d/core/functions_warcpy.py#L954
https://github.com/esturdivant-usgs/BI-geomorph-extraction/blob/9d850847209610eff0c0408c6479d018f7b78b9d/core/setvars.py#L18
https://github.com/esturdivant-usgs/BI-geomorph-extraction/blob/9d850847209610eff0c0408c6479d018f7b78b9d/core/setvars.py#L23
Also see `prepper.ipynb` for the same issue. Not sure if all of the absolute paths are required to be masked, though.

Temp folder is already marked by the author for deletion and I agree with that because folder it has scripts with absolute file  system paths.

**Comment by esturdivant-usgs** [comment]
Removed temp folder and prepper notebook. Removed line `# 12 minutes for FireIsland` but preserved the example file path in the user input prompt because it is generic and does not provide information about computer configuration. 

87f107bbd6a6a1ff5d14e7c9dbae08540372d1a6
