### ISSUE TITLE
Review comment #3: remove prepper notebook

### ISSUE THREAD

**Issue by csherwood-usgs** [esturdivant-usgs/BI-geomorph-extraction#37]
We agreed that the prepper notebook would be removed, and the products it produces be published.

**Comment by esturdivant-usgs** [comment]
This requires publishing the following files in addition to those that were already planned:
- tidyTransects
- inletLines and armorLines?

**Comment by esturdivant-usgs** [comment]
Removed in commit 87f107bbd6a6a1ff5d14e7c9dbae08540372d1a6
