### ISSUE TITLE
Review comment #4

### ISSUE THREAD

**Issue by csherwood-usgs** [esturdivant-usgs/BI-geomorph-extraction#38]
We made some notes as we ran through extractor, and identified a few places where missing files or variable that needed to be commented out caused errors.

We also agree that extractor would actually be an example from a specific field site,  and not designed for a naive first-time user.

If those are fixed, extractor looks like it is ready to publish

**Comment by esturdivant-usgs** [comment]
Addressed these comments in the last two commits (75251ec443891d9d77eeaaa2fb5148301eceacc3 and bb6a388). Still need to perform test run with iterative troubleshooting.
